# Generated by Django 3.2 on 2021-04-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='important',
            field=models.IntegerField(choices=[(0, 'Нет оценки'), (1, 'Неважно'), (2, 'Важно'), (3, 'Оченб важно')], default=0, verbose_name='Статус важности'),
        ),
    ]
