# Generated by Django 3.2 on 2021-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_notebook_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Статус важности'),
        ),
    ]
